# Generated by Django 5.2.7 on 2025-12-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialOffer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='special_offers/'),
        ),
    ]
