# Generated by Django 5.2.7 on 2026-01-12 16:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialOffer', '0002_alter_specialoffer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
